### ISSUE TITLE
bug in initialization of variable splitter?

### ISSUE THREAD

**Issue by mlivesu** [danshapero/predicates#12]
Hi, thanks for this code!

according to Shewchuck's doubleprint(), the value of the global variable **splitter** after executing _exactinit()_ and after your initialization with **((DBL_MANT_DIG + 1) >> 1) + 1.0** is different.  

As a result, for these four coplanar points:

V0 : 7.878286361694336, -21.723194122314453, -13.910694122314453
V1 : 7.827281951904297, -21.42486572265625, -13.61236572265625
V2 : 7.860530853271484, -21.5969181060791, -13.784418106079102
V3 : 7.077847957611084, -21.82772445678711, -14.01522445678711

orient3d(V0,V1,V2,V3) != orient(V2,V3,V0,V1), 

which is clearly a bug.

After experimenting a bit, I found that initializing splitter with **(1 << (DBL_MANT_DIG/2+1) + 1.0** gives the same result as the one produce by _exactinit()_. 

To be bloody honest, I am not sure I fully understand why: I would have expected the correct initialization to be **(1 << (DBL_MANT_DIG/2)) + 1.0**. Anyways, I tested both initializations, and they both seem to fix the orient predicates. You may want to fix your code as well.

Cheers,
cino

**Comment by danshapero** [comment]
Thanks for the catch, especially for the test case! I've included that as a regression test now. I haven't looked at this repo in years so I can't even remember why I thought that formula for `splitter` would work.
