### ISSUE TITLE
Constant value defined by global initialization in "constant.c" can be inexact

### ISSUE THREAD

**Issue by flm8620** [danshapero/predicates#8]
The original code by Shewchuk use a `void exactinit();` to initialize some global values like machine epsilon, bound etc. Your library replaced it by `extern const double` declaration with a inline initialization like

`const double splitter = ((DBL_MANT_DIG + 1)>>1)+1.0`

I think these assignment might not be exact, because they are computed by compiler, not at run time.
I tested in Visual Studio 2015 x64, with flag /fp:strict.
And I got inexact result for test :

```
orient2d(p,q,r) with:
p=(12.0000000000000107, 12.0000000000000195)
q=(24.0, 24.0)
r=(0.5, 0.5) + (i,j)*(machine epsilon), -200<i,j<200
```

The original code by Shewchuk doesn't have this problem.

**Comment by danshapero** [comment]
Thanks for the catch! I'll try and reproduce this on a windows machine.

Can you share a file with all of the `i, j` values for which you find an incorrect result, as well as the complete program and compiler flags that you found them with? That would help me track this down and possibly find a workaround.

**Comment by flm8620** [comment]
I'll print out the exact double number created as global constant by compiler and also the same group of double created by `exactinit()` and check the difference

**Comment by flm8620** [comment]
bug found. It's not the problem of Visual studio.

This line in "constant.c" is wrong:
```
const double splitter = ((DBL_MANT_DIG + 1) >> 1) + 1.0;
```
It should be
```
const double splitter = ( 1 << ((DBL_MANT_DIG + 1) >> 1)) + 1.0;
```
